# Generated by Django 2.2.1 on 2019-09-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rythubazarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Adress',
            new_name='Address',
        ),
    ]
