# Generated by Django 2.2.1 on 2019-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rythubazarapp', '0002_auto_20190908_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='cropimage',
            field=models.ImageField(blank=True, default='', upload_to='../static/images/'),
        ),
    ]
