# Generated by Django 2.2.1 on 2019-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rythubazarapp', '0003_auto_20190908_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='cropimage',
            field=models.ImageField(blank=True, default='../static/images/', upload_to=''),
        ),
    ]
