# Generated by Django 2.2.1 on 2019-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rythubazarapp', '0004_auto_20190908_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='cropimage',
            field=models.ImageField(blank=True, default='G:\\rythu\\rythubazar\\static', upload_to=''),
        ),
    ]
